config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
  }
  devise_scope :user do
    get 'addresses', to: 'users/registrations#new2'
    post 'addresses', to: 'users/registrations#new3'
  end
  root 'items#index'

  # itemコントローラーrouting
  resources :items do
    member do
      get 'category_children', defaults: { format: 'json' }
      get 'category_grandchildren', defaults: { format: 'json' }
    end

    resources :transactions do
      member do
        get  :confirm
        post :transacte
        get :carderror
      end
    end
    collection do
      get 'search'
    end
   
    
  end

  resources :users, only: [:show] do
    collection do
      get :logout
    end
  end 

  resources :card, only: [:new, :create, :show, :destroy]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
    mount_uploader :image, ImageUploader

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # アソシエーション
  has_many :evaluations,  dependent: :destroy
  has_one  :card,         dependent: :destroy
  has_many :informations, dependent: :destroy
  has_many :items
  has_many :comments
  has_many :transactions
  has_many :messages
  has_one  :address,        dependent: :destroy

  # 以下バリデーション
  # 空ではないこと
  validates :nickname, :first_name, :last_name, :first_name_kana, :last_name_kana, :birthday, :money, :point, presence: true

  # 氏名、ふりがなは全角で入力すること
  # 全角カタカナ、ひらがな、漢字
  validates :first_name, :last_name, format: { with: /\A[ぁ-んァ-ン一-龥]/ }
  # 全角カタカナ
  validates :first_name_kana, :last_name_kana, format: { with: /\A[ァ-ヶー－]+\z/ }

  # 一意性であること(ニックネーム、メールアドレス)
  validates :nickname, :email, uniqueness: true

  # 一致していること, ７文字以上であること（パスワード）
  validates :password, confirmation: true, length: { minimum: 7 }

  # メールアドレスは@とドメインを含むこと
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, format: { with: VALID_EMAIL_REGEX }

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    @user=User.new
  end

  def create
    @user = User.new(user_params)
    unless @user.valid?
      render :new and return
    end
    session["devise.regist_data"] = {user: @user.attributes}
    session["devise.regist_data"][:user]["password"] = params[:user][:password]
    @address = @user.build_address

    render :new2
  end

  def new3
    @user = User.new(session["devise.regist_data"]["user"])
    @address = Address.new(address_params)
    unless @address.valid?
      flash.now[:alert] = @address.errors.full_messages
      render :new2 and return
    end
  
    @user.build_address(@address.attributes)
    @user.save
    session["devise.regist_data"]["user"].clear
    sign_in(:user, @user)
  end


  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
  protected

  def address_params
    params.require(:address).permit(:sending_first_name, :sending_last_name, :sending_first_name_kana, :sending_last_name_kana, :postal_code, :prefecture_id, :city, :town, :building, :phone)
  end
  def user_params
    params.require(:user).permit(:nickname, :email, :password, :password_confirmation, :first_name, :last_name, :first_name_kana, :last_name_kana,:image, :birthday)
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_breadcrumb.html.haml
.breadcrumb
  = breadcrumbs pretext: "",separator: "&rsaquo; "

app/views/users/_leftbar.html.haml
.left-content
  .left-content__menu
    .left-content__menu__list
      %li
      = link_to "マイページ", "#", class: "left-content__menu__list--item"
      %li
      = link_to "お知らせ", "#", class: "left-content__menu__list--item" 
      %li
      = link_to "やることリスト", "#", class: "left-content__menu__list--item"
      %li
      = link_to "いいね！一覧", "#", class: "left-content__menu__list--item"
      %li
      = link_to "出品する", "#", class: "left-content__menu__list--item"
      %li
      = link_to "下書き一覧", "#", class: "left-content__menu__list--item"
      %li
      = link_to "出品した商品-出品中", "#", class: "left-content__menu__list--item"
      %li
      = link_to "出品した商品-取引中", "#", class: "left-content__menu__list--item"
      %li
      = link_to "出品した商品-売却済み", "#", class: "left-content__menu__list--item"
      %li
      = link_to "購入した商品-取引中", "#", class: "left-content__menu__list--item"
      %li
      = link_to "購入した商品-過去の取引", "#", class: "left-content__menu__list--item"
      %li
      = link_to "ニュース一覧", "#", class: "left-content__menu__list--item"
      %li
      = link_to "評価一覧", "#", class: "left-content__menu__list--item"
      %li
      = link_to "ガイド", "#", class: "left-content__menu__list--item"
      %li
      = link_to "お問い合わせ", "#", class: "left-content__menu__list--item"
      %h3.left-content__menu__list__bar フリマペイ
      %li
      = link_to "売上・申込申請", "#", class: "left-content__menu__list--item"
      %li
      = link_to "ポイント", "#", class: "left-content__menu__list--item"
      %h3.left-content__menu__list__bar 設定
      %li
      = link_to "プロフィール", "#", class: "left-content__menu__list--item"
      %li
      = link_to "発送元・お届け先", "#", class: "left-content__menu__list--item"
      %li
      = link_to "支払い方法", new_card_path, class: "left-content__menu__list--item"
      %li
      = link_to "メール/パスワード", "#", class: "left-content__menu__list--item"
      %li
      = link_to "本人情報", "#", class: "left-content__menu__list--item"
      %li
      = link_to "電話番号確認", "#", class: "left-content__menu__list--item"
      %li
      = link_to "ログアウト", logout_users_path, class: "left-content__menu__list--item"

app/views/users/_right-main.html.haml
.right-main
  .right-main__block#back-image.in-main
    = image_tag current_user.image.url, height: '60', width: '60', alt: 'user-icon', class: 'user-icon'
    .right-main__block__user-name #{current_user.nickname}
    .right-main__block__user-about
      .right-main__block__review 評価
      .right-main__block__exhibit 出品数

  .right-main__block__1
    .right-main__block__1__tab-heads
      %li
        .right-main__block__1__active
          お知らせ
      %li
        .right-main__block__1__todo
          やることリスト
  
  .right-main__block__object
    .right-main__block__object__link-box
      = image_tag '', alt: '', height: '48', width: '48', class: 'right-main__object__link-box__image'
      .right-main__block__object__link-box__body
        .right-main__block__object__link-box__body--text 《まだ間に合う》まとめて出品して１万名にP3,000当たる!
        .right-main__block__object__link-box__body--time
          %i.far.fa-clock
          .right-main__block__object__link-box__body--time--date 1日前
      -# %i.fa.fa-angle-right

    .right-main__block__object__link-box
      = image_tag '', alt: '', height: '48', width: '48', class: 'ight-main__object__link-box__image'
      .right-main__block__object__link-box__body
        .right-main__block__object__link-box__body--text  事務局から個別メッセージ「ログイン通知」
        .right-main__block__object__link-box__body--time
          %i.far.fa-clock
          .right-main__block__object__link-box__body--time--date 3日前
      -# %i.fa.fa-angle-right

    .right-main__block__object__link-box
      = image_tag '', alt: '', height: '48', width: '48', class: 'ight-main__object__link-box__image'
      .right-main__block__object__link-box__body
        .right-main__block__object__link-box__body--text 《飲食店で20%ポイント還元》フリマペイ登録で還元率が50%に!!
        .right-main__block__object__link-box__body--time
          %i.far.fa-clock
          .right-main__block__object__link-box__body--time--date 5日前
      -# %i.fa.fa-angle-right

    .right-main__block__object__link-box
      = image_tag '', alt: '', height: '48', width: '48', class: 'ight-main__object__link-box__image'
      .right-main__block__object__link-box__body
        .right-main__block__object__link-box__body--text 《桜キャンペーン》いらないものを売ってみよう！
        .right-main__block__object__link-box__body--time
          %i.far.fa-clock
          .right-main__block__object__link-box__body--time--date 5日前
      -# %i.fa.fa-angle-right

    .right-main__block__object__link-box
      = image_tag '', alt: '', height: '48', width: '48', class: 'ight-main__object__link-box__image'
      .right-main__block__object__link-box__body
        .right-main__block__object__link-box__body--text 《あと2日》今なら出品して１万名にP3,000当たる!
        .right-main__block__object__link-box__body--time
          %i.far.fa-clock
          .right-main__block__object__link-box__body--time--date 10日前
      -# %i.fa.fa-angle-right

    .right-main__block__object__link-box
      = image_tag '', alt: '', height: '48', width: '48', class: 'ight-main__object__link-box__image'
      .right-main__block__object__link-box__body
        .right-main__block__object__link-box__body--text  事務局から個別メッセージ「衛生マスクの出品禁止について」
        .right-main__block__object__link-box__body--time
          %i.far.fa-clock
          .right-main__block__object__link-box__body--time--date 10日前
      -# %i.fa.fa-angle-right

    .right-main__block__object__link-box
      .right-main__block__object__link-box__content
        .right-main__block__object__link-box__content__chart 一覧を見る

  .right-main__block--bar
    .right-main__block__2
      %li
        .right-main__block__2__bar
          購入した商品
    .right-main__block__2__tab-heads
      %li
      .right-main__block__2__tab-heads__transaction
        取引中
      .right-main__block__2__tab-heads__past
        過去の取引
    %ul.right-main__block__2__none
      %li.right-main__block__2__none--list
        取引中の商品がありません

app/views/users/logout.html.haml
= render "items/header"
- breadcrumb :logout
= render "users/breadcrumb"
.mypage-main-conent
  .mypage-main-index
    = render "users/leftbar"
    
  .right-content
    .logout
      .logout__content
        .logout__content__container
          = link_to "ログアウト", destroy_user_session_path, method: :delete, class: "logout__content__container--btn"

= render "items/banner"
= render "items/exhibition-btn"
= render "items/footer"

app/views/users/show.html.haml
= render "items/header"
- breadcrumb :mypage
= render "users/breadcrumb"
.mypage-main-conent
  .mypage-main-index
    = render "users/leftbar"
  .right-content
    = render "users/right-main"

= render "items/banner"
= render "items/exhibition-btn"
= render "items/footer"