config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
  }
  devise_scope :user do
    get 'addresses', to: 'users/registrations#new2'
    post 'addresses', to: 'users/registrations#new3'
  end
  root 'items#index'

  # itemコントローラーrouting
  resources :items do
    member do
      get 'category_children', defaults: { format: 'json' }
      get 'category_grandchildren', defaults: { format: 'json' }
    end

    resources :transactions do
      member do
        get  :confirm
        post :transacte
        get :carderror
      end
    end
    collection do
      get 'search'
    end
   
    
  end

  resources :users, only: [:show] do
    collection do
      get :logout
    end
  end 

  resources :card, only: [:new, :create, :show, :destroy]
end

app/models/item.rb
class Item < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :condition
  belongs_to_active_hash :delivery_charge
  belongs_to_active_hash :sending_days
  belongs_to_active_hash :shipping_origin
  has_many :item_images, dependent: :destroy
  accepts_nested_attributes_for :item_images,allow_destroy: true
  belongs_to :user
  belongs_to :category
  has_one :tx, class_name: 'Transaction'

  # scope
  # カテゴリごとにアイテムを６つまで取得する
  scope :get_category, -> (number) { where(category_id: Category.where(ancestry:nil).find(number).indirects).limit(6) }
  
  # バリデーション
  validates :name, :user_id, :item_images, :category_id,  :transaction_status, :sending_days_id, :shipping_origin_id, :delivery_charge_id, :condition_id, presence: true
  validates :price, presence: true, numericality: {only_integer: true, greater_than: 299, less_than: 9999999}
  validates :explanation, presence: true, length: { maximum: 1000 }
  def self.search(search)
    return Item.all unless search
    query = [(['name LIKE ?'] * search.split(/[[:blank:]]+/).length).join(' AND ')] + search.split(/[[:blank:]]+/).map { |name| "%#{name}%" }
    Item.where(*query) 
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :move_to_index, except: [:index, :show, :search]
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  before_action :set_parent_category, only: [:new, :create, :edit, :update]


  
  def index
    @items = Item.includes(:item_images).order('created_at DESC').limit(3).where.not(transaction_status: 0).where(transaction_status: 1)
    @ladies_items = @items.get_category(1)
    @mens_items   = @items.get_category(2)
    @babies_items = @items.get_category(3)
  end

  def new
    @parent = Category.where(ancestry: nil)
    @item = Item.new
    @item.item_images.new
  end

  def create
    @parent = Category.where(ancestry: nil)
    @item= Item.new(item_params)
    if @item.save
     redirect_to root_path
    else
     render :new
    end
  end


  def show
  end

  def edit
    @images_length = @item.item_images.length
    @grandchildren = Category.where(ancestry: @item.category.ancestry)
    @children = Category.where(ancestry: @item.category.parent.ancestry)
  end

  def update
      if @item.user_id == current_user.id && @item.update(item_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    if @item.destroy
      redirect_to root_path
    else
      redirect_to item_path(@item.id)
    end
  end

  def category_children
    respond_to do |format|
      format.html
      format.json do
        @category_children = Category.find(params[:parent_id]).children
      end
    end
  end

  def category_grandchildren
    respond_to do |format|
      format.html
      format.json do
        @category_grandchildren = Category.find(params[:child_id]).children
      end
    end
  end

  def search
    if params[:keyword].present?
    @items_search = Item.search(params[:keyword]).order(updated_at:"DESC").where(transaction_status: "1")
    @keyword=params[:keyword]
    else
      redirect_to  root_path
    end
  end

  private

  def item_params
    params.require(:item).permit(:name, :price, :category_id, :brand, :explanation,:condition_id,:delivery_charge_id,:shipping_origin_id,:sending_days_id,item_images_attributes: [:image,:_destroy, :id]).merge(user_id:current_user.id)
  end

  def move_to_index
    redirect_to new_user_session_path unless user_signed_in?
  end

  def set_item
    @item = Item.find(params[:id])
  end

  def set_parent_category
    @parent = Category.where(ancestry: nil)
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_banner.html.haml
.top-banner
  .top-banner__body
    %h2.top-banner__body__title
      だれでもかんたん、人生を変えるフリマアプリ
    %p.top-banner__body__text
      今すぐ無料ダウンロード!
    .top-banner__body__icon
      = link_to image_tag("icon/app-store-9c5e28e8f81bd9912e0ded2f78821e04778a1356c05dc7c7bf1e88614be37c34.svg", class:"apple-btn dlbtn"), '#'
      = link_to image_tag("icon/google-play-469c63f1269e456307c4dde176b33cc3bbbbf142ac4d7369656010130149db1a.svg", class:"google-btn dlbtn"), '#'

app/views/items/_exhibition-btn.html.haml
= link_to new_item_path, class: "exhibition" do
  .exhibition__btn
    %span.exhibition__btn__text
      出品する
    = image_tag "icon/icon_camera.png", class: "exhibition__btn__image"

app/views/items/_exhibition.html.haml
= render 'header'
.wrapper-item
 .ex#form-name
  =form_with model:@item, url:items_path, local: true  do |exh|
   .ex__image
    .ex__image--title
     .ex__image--title--exp
      画像
     .ex__image--title--must.must
      必須
    .ex__image--photo
     画像は１０枚まで
    .ex__image--upload#previews
     - if @item.persisted?
      - @item.images.each_with_index do |image, i|
       = image_tag image.src.url, data: { index: i }, width: "100", height: '100'
    .ex__image--upload#image-box
     =exh.fields_for :item_images,class:"validate[required]" do |img|
      .js-file_group{"data-index": "#{img.index}"}
       = img.file_field :image, class: 'js-file'
       %span.js-remove 削除
      -if @item.persisted?
       = img.check_box :_destroy, data:{ index: img.index }, class: 'hidden-destroy'
      -if @item.persisted?
       .js-file_group{"data-index" => "#{@item.item_images.count}"}
       = file_field_tag :image, name: "product[images_attributes][#{@item.item_images.count}][image]", class: 'js-file'
   .ex__intro
    .ex__intro__name
     .ex__intro__name--exp
      商品名
     .ex__intro__name--must.must
      必須
    .ex__intro__exp
     =exh.text_field :name,class:'text-form forms validate[required] validate[maxSize] ',placeholder:'商品名を入力してください'
    .ex__intro__exp--exp
     說明
     .ex__intro__exp--must.must
      必須
    .ex__intro__duce
     =exh.text_area :explanation,class:'text-duce forms validate[required]',placeholder:'商品の說明を入力してください'
    .ex__intro__strcount
     0/1,000
   .ex__detail
    .ex__detail--first
     商品詳細
     // カテゴリ
    .ex__detail__category
     .ex__detail__category--in
      カテゴリを選択してください
     .ex__detail__category--must.must 必須
    .ex__detail__category__box
     = exh.select :category, @category_parent_array, {}, {class: 'ex__detail__category__box--select select', id: 'parent-form'}
    // ブランド
    .ex__detail__brand
     .ex__detail__brand--in
      ブランドを選択してください
     .ex__detail__brand--free.free
      任意
    .ex__detail__brand--select
     =exh.text_field :brand,class:'text-form',placeholder:'ブランド名を入力してください'
    .ex__detail__status
     .ex__detail__status--in
      状態を選んでください
     .ex__detail__status--must.must
      必須
    .ex__detail__status--select
     = exh.collection_select :condition_id, Condition.all, :id, :name, {prompt: "--"},{class:"  select validate[required]"}
   .ex__deliver
    .ex__deliver--first
     配送について
    .ex__deliver__fee
     .ex__deliver__fee--in
      配送料の負担
     .ex__deliver__fee--must.must
      必須
    .ex__deliver__fee--select
     = exh.collection_select :delivery_charge_id, DeliveryCharge.all, :id, :name, {prompt: "--"},{class:"  select validate[required]"}
    .ex__deliver__land
     .ex__deliver__land--in
      配送先
     .ex__deliver__land--must.must
      必須
    .ex__deliver__land--select
     = exh.collection_select :shipping_origin_id, Prefecture.all, :id, :name, {prompt: "--"},{class:"  select validate[required]"}
    .ex__deliver__date
     .ex__deliver__date--in
      日数
     .ex__deliver__date--must.must
      必須
    .ex__deliver__date--select
     = exh.collection_select :sending_days_id, SendingDays.all, :id, :name, {prompt: "--"},{class:"  select validate[required]"}
   .ex__price
    .ex__price--in
     価格　(¥300~¥10,000,000)
    .ex__price__money
     .ex__price__money__left
      .ex__price__money__left--string
       値段
      .ex__price__money__left--must.must
       必須
     .ex__price__money--pay
      .ex__price__money--pay--mark
       ¥
      .ex__price__money--pay--form
       =exh.text_field :price,class:'text-money money_form validate[required]',placeholder:'希望金額を入力してください',type:"number"
    .ex__price__fee
     .ex__price__fee--string
      手数料
     .ex__price__fee--real-fee
      ここに手数料を表示
    .ex__price__benefit
     .ex__price__benefit--in
      あなたの利益
     .ex__price__benefit--mouke
      ここに利益金額を表示
   .ex__go
    .ex__go__menu
     .ex__go__menu--done
      =exh.submit "出品する",class:"gobutton"
     .ex__go__menu--back
      =link_to 'トップページへ',items_path
= render 'footer'

app/views/items/_footer.html.haml
%footer.footer
  %ul.footer__body
    %li.footer__body__content
      %h2.footer__body__content__title
        FURIMAについて
      %ul.footer__body__content__lists
        %li= link_to '会社概要（運営会社）', '#',class:"footer__body__content__lists__list footer-link"
        %li= link_to 'プライバシーポリシー', '#',class:"footer__body__content__lists__list footer-link"
        %li= link_to 'FURIMA利用規約', '#',class:"footer__body__content__lists__list footer-link"
        %li= link_to 'ポイントに関する特約', '#',class:"footer__body__content__lists__list footer-link"
    %li.footer__body__content
      %h2.footer__body__content__title
        FURIMAを見る
      %ul.footer__body__content__lists
        %li= link_to 'カテゴリー一覧', '#',class:"footer__body__content__lists__list footer-link"
        %li= link_to 'ブランド一覧', '#',class:"footer__body__content__lists__list footer-link"
    %li.footer__body__content  
      %h2.footer__body__content__title
        ヘルプ＆ガイド
      %ul.footer__body__content__lists
        %li= link_to 'FURIMAガイド', '#',class:"footer__body__content__lists__list footer-link"
        %li= link_to 'FURIMAロゴ利用ガイドライン', '#',class:"footer__body__content__lists__list footer-link"
        %li= link_to 'お知らせ', '#',class:"footer__body__content__lists__list footer-link"
  .footer__logo
    = link_to image_tag("logo/logo-white.png", class:"footer__logo__icon"), root_path
    %p.footer__logo__text
      ©︎ FURIMA

app/views/items/_header.html.haml
%header.header
  .header__body
    .header__body__main
      .header__body__main__icon-area
        = link_to image_tag("logo/logo.png", class: "header__body__main__icon-area__icon"), root_path
      .header__body__main__search
        = form_with(url: search_items_path, local: true, method: :get, class: "header__body__main__search__form") do |f|
          = f.text_field :keyword, placeholder: "キーワードから探す", class: "header__body__main__search__form__input"
          %label.header__body__main__search__form__submit
            = f.submit "", class:"header__body__main__search__form__submit__btn"
            = image_tag "icon/icon-search 1.png", class:"header__body__main__search__form__submit__image"
    .header__body__nav
      %ul.nav-left
        %li.nav-left__content.nav-left__content--category
          = link_to "カテゴリー", "#", class: "header-link"
        %li.nav-left__content
          = link_to "ブランド", "#", class: "header-link"
      %ul.nav-right
        - if user_signed_in?
          %li.nav-right__content.nav-right__content--in
            = link_to user_path(current_user), class: "header-link mypage-link" do
              = image_tag current_user.image.url, class: "mypage-link__image" 
              %p #{current_user.nickname}
        - else
          %li.nav-right__content.nav-right__content--out
            = link_to "ログイン", new_user_session_path, class: "header-link"
          %li.nav-right__content.nav-right__content--new
            = link_to "新規会員登録", new_user_registration_path, class: "header-link"

app/views/items/_item-list.html.haml
.top-item-list
  .top-item-container

    %h2.top-item-container__title
      レディース新着アイテム
    .top-item-container__contents
      %ul.top-items.top-items--login
        - @ladies_items.each do |item|
          = render partial: "top-item", locals: { item: item}

    %h2.top-item-container__title
      メンズ新着アイテム
    .top-item-container__contents
      %ul.top-items.top-items--login
        - @mens_items.each do |item|
          = render partial: "top-item", locals: { item: item}
      
    %h2.top-item-container__title
      ベビー・キッズ新着アイテム
    .top-item-container__contents
      %ul.top-items.top-items--login
        - @babies_items.each do |item|
          = render partial: "top-item", locals: { item: item}

app/views/items/_top-item.html.haml
%li.top-items__list
  = link_to item_path(item), class: "top-items__list__link" do
    %figure.top-items__list__link__image
      = image_tag "#{item.item_images.first.image}" if item.item_images.present?
    .top-items__list__link__body
      %h3.top-items__list__link__body__name
        #{item.name}
      .top-items__list__link__body__explanation
        %ul
          %li
            #{item.price}円
          %li
            %i.fas.fa-star
            #{item.likes}
        %p
          (税込) 

app/views/items/_toppage.html.haml
.toppage_contents
  %section.top-visual
    .top-visual__content
      %h2.top-visual__content__title
        人生を変えるフリマアプリ
      %p.top-visual__content__subtitle
        フリマはだれでもかんたんに出品・購入できる
        %br
          フリマアプリです
      .top-visual__content__btn
        = link_to image_tag("icon/app-store-9c5e28e8f81bd9912e0ded2f78821e04778a1356c05dc7c7bf1e88614be37c34.svg", class: "apple-btn dlbtn"), '#'
        = link_to image_tag("icon/google-play-469c63f1269e456307c4dde176b33cc3bbbbf142ac4d7369656010130149db1a.svg", class: "google-btn dlbtn"), '#'
  
  %section.top-introduction
    %h2.top-introduction__title
      FURIMAが選ばれる３つの理由
    %ul.top-introduction__lists
      %li.top-introduction__lists__list
        .top-introduction__lists__list__picture
          %span.top-introduction__lists__list__picture__number
            1
          = image_tag "pict/pict-reason-01.jpg", class: "top-introduction__lists__list__picture__image"
        %h3.top-introduction__lists__list__title
          %span
            ３分
          ですぐに出品
        %p.top-introduction__lists__list__explanation
          スマホで入力するだけで簡単に出品できる     
      %li.top-introduction__lists__list
        .top-introduction__lists__list__picture
          %span.top-introduction__lists__list__picture__number
            2
          = image_tag "pict/pict-reason-02.jpg", class: "top-introduction__lists__list__picture__image"
        %h3.top-introduction__lists__list__title
          %span
            シンプル
          で使いやすい
        %p.top-introduction__lists__list__explanation
          めんどくさい入力は必要なく、検索も購入もスムーズ!

      %li.top-introduction__lists__list
        .top-introduction__lists__list__picture
          %span.top-introduction__lists__list__picture__number
            3
          = image_tag "pict/pict-reason-03.jpg", class: "top-introduction__lists__list__picture__image"
        %h3.top-introduction__lists__list__title
          手数料
          %span
            業界最安
        %p.top-introduction__lists__list__explanation
          最大3%でお得に出品&購入!
  %section.top-membership
    .top-membership__body
      %h2.top-membership__body__title
        会員数日本一位
      %p.top-membership__body__text
        FURIMAは、フリマアプリで最も人気。
        %br
        出品・購入回数も業界最多です！
        %br
        ほしかったあの商品に出会えるかもしれません。
      .top-membership__body__btn
        = link_to image_tag("icon/app-store-9c5e28e8f81bd9912e0ded2f78821e04778a1356c05dc7c7bf1e88614be37c34.svg", class:"apple-btn dlbtn"), '#'
        = link_to image_tag("icon/google-play-469c63f1269e456307c4dde176b33cc3bbbbf142ac4d7369656010130149db1a.svg", class:"google-btn dlbtn"), '#'
    = image_tag "", class: "top-membership__picture"
  %section.top-characteristic
    .top-characteristic__title
      FURIMAの特徴
    .top-characteristic__lists
      .top-characteristic__lists__list
        = image_tag "icon/icon-01.png", class: "top-characteristic__lists__list__picture"
        .top-characteristic__lists__list__title
          簡単に売り買いできる
        .top-characteristic__lists__list__text
          スマホひとつで、いつでもどこでも簡単に出品・購入が可能！

      .top-characteristic__lists__list
        = image_tag "icon/icon-03.png", class: "top-characteristic__lists__list__picture"
        .top-characteristic__lists__list__title
          売上金は即日振込みに対応
        .top-characteristic__lists__list__text
          午前９時までに振込を依頼いただければ、翌日に指定の銀行に入金いたします！

      .top-characteristic__lists__list
        = image_tag "icon/icon-04.png", class: "top-characteristic__lists__list__picture"
        .top-characteristic__lists__list__title
          様々な支払いに対応
        .top-characteristic__lists__list__text
          お支払いは、クレジットカードだけでなく、ポイントや売上金など多彩な方法があります。

  %section.top-pickup
    %h2.top-pickup__title
      ピックアップカテゴリー
    .top-pickup__subtitle
      新規投稿商品
    %ul.top-items
      - @items.each do |item|
        = render partial: "top-item", locals: { item: item}
  %section.top-pickup
    %h2.top-pickup__title
      ピックアップブランド
    .top-pickup__subtitle
      アーカイバ
    %ul.top-items
      - @items.each do |item|
        = render partial: "top-item", locals: { item: item}

app/views/items/edit.html.haml
= render 'header'
.wrapper-item
 .ex#form-name
  =form_with model:@item, url:item_path, local: true  do |exh|
   .ex__image
    .ex__image--title
     .ex__image--title--exp
      画像
     .ex__image--title--must.must
      必須
    .ex__image--photo
     画像は１０枚まで
    .ex__image--upload#previews

     - if @item.persisted?
      - @item.item_images.each_with_index do |image,i|
       .image-menu{"data-index" => "#{i}"}
        = image_tag image.image_url ,data: { index: i }, width: "120px", height: '120px'
        %span.js-remove.add
         取り消す
    .ex__image--upload.editform#image-box
     =exh.fields_for :item_images,class:"validate[required]" do |img|
      %label.js-file_group{"data-index": "#{img.index}"}
       =img.label :image ,class:'label js-file' do
        = img.file_field :image, class: 'none'
        = img.check_box :_destroy, data:{ index: img.index }, class: 'hidden-destroy'
        .sub-image
         画像を設定する

   .ex__intro
    .ex__intro__name
     .ex__intro__name--exp
      商品名
     .ex__intro__name--must.must
      必須
    .ex__intro__exp
     =exh.text_field :name,class:'text-form forms validate[required] validate[maxSize] ',placeholder:'商品名を入力してください'
    .ex__intro__exp--exp
     說明
     .ex__intro__exp--must.must
      必須
    .ex__intro__duce
     =exh.text_area :explanation,class:'text-duce forms validate[required]',placeholder:'商品の說明を入力してください'
    .ex__intro__strcount
     0/1,000
   .ex__detail
    .ex__detail--first
     商品詳細
     // カテゴリ
    .ex__detail__category
     .ex__detail__category--in
      カテゴリを選択してください
     .ex__detail__category--must.must 必須
    .ex__detail__category__box
     = exh.collection_select :category_id, @parent, :id, :name, { prompt: "選択してください" ,selected: @item.category.root.id}, { class: "ex__detail__category__box--select select validate[required]", id: "parent-form" }
     = exh.collection_select :category_id, @children, :id, :name, { prompt: "選択してください" ,selected: @item.category.parent.id}, { class: "ex__detail__category__box--select select validate[required]", id: "child-form" }
     = exh.collection_select :category_id, @grandchildren, :id, :name, { prompt: "選択してください" ,selected: @item.category.id}, { class: "ex__detail__category__box--select select validate[required]", id: "grandchild-form" }
    // ブランド
    .ex__detail__brand
     .ex__detail__brand--in
      ブランドを選択してください
     .ex__detail__brand--free.free
      任意
    .ex__detail__brand--select
     =exh.text_field :brand,class:'text-form',placeholder:'ブランド名を入力してください'
    .ex__detail__status
     .ex__detail__status--in
      状態を選んでください
     .ex__detail__status--must.must
      必須
    .ex__detail__status--select
     = exh.collection_select :condition_id, Condition.all, :id, :name, {prompt: "--"},{class:"  select validate[required]"}
   .ex__deliver
    .ex__deliver--first
     配送について
    .ex__deliver__fee
     .ex__deliver__fee--in
      配送料の負担
     .ex__deliver__fee--must.must
      必須
    .ex__deliver__fee--select
     = exh.collection_select :delivery_charge_id, DeliveryCharge.all, :id, :name, {prompt: "--"},{class:"  select validate[required]"}
    .ex__deliver__land
     .ex__deliver__land--in
      配送先
     .ex__deliver__land--must.must
      必須
    .ex__deliver__land--select
     = exh.collection_select :shipping_origin_id, Prefecture.all, :id, :name, {prompt: "--"},{class:"  select validate[required]"}
    .ex__deliver__date
     .ex__deliver__date--in
      日数
     .ex__deliver__date--must.must
      必須
    .ex__deliver__date--select
     = exh.collection_select :sending_days_id, SendingDays.all, :id, :name, {prompt: "--"},{class:"  select validate[required]"}
   .ex__price
    .ex__price--in
     価格　(¥300~¥10,000,000)
    .ex__price__money
     .ex__price__money__left
      .ex__price__money__left--string
       値段
      .ex__price__money__left--must.must
       必須
     .ex__price__money--pay
      .ex__price__money--pay--mark
       ¥
      .ex__price__money--pay--form
       =exh.text_field :price,class:'text-money money_form validate[required]',placeholder:'希望金額を入力してください',type:"number"
    .ex__price__fee
     .ex__price__fee--string
      手数料
     .ex__price__fee--real-fee
      ここに手数料を表示
    .ex__price__benefit
     .ex__price__benefit--in
      あなたの利益
     .ex__price__benefit--mouke
      ここに利益金額を表示
   .ex__go
    .ex__go__menu
     .ex__go__menu--done
      =exh.submit "更新する",class:"gobutton"
     .ex__go__menu--back
      =link_to 'トップページへ',items_path
= render 'footer'

app/views/items/index.html.haml
= render 'header'
- if user_signed_in?
  = render 'item-list' 
- else 
  = render 'toppage'
= render 'banner'
= render 'exhibition-btn'
= render 'footer'

app/views/items/search.html.haml
= render 'header'
.top-item-list
  .top-item-container
    %h2.top-item-container__title
      "#{@keyword}"で検索した結果
    - if @items_search.present?
      .top-item-container__contents
        %ul.top-items.top-items--login
          - @items_search.each do |item|
            = render partial: "top-item", locals: { item: item}
    - else
      .top-item-container__contents.nothing
        条件に一致する商品はありませんでした。
= render 'banner'
= render 'exhibition-btn'
= render 'footer'

app/views/items/show.html.haml
= render 'header'
.wrapper-item
 .de
  .de__name
   = @item.name
  .de__image
   = image_tag "#{@item.item_images.first.image}", width: "560", height: "350", class: "de__image__main"
  .de__image-list
   .de__image-list__box
    .de__image-list__box--img
    - @item.item_images.each do |image|
     = image_tag "#{image.image.url}", width: "108", height: "100", class: "de__image-list__box--img--1"
  .de__price
   .de__price--price
    = "¥#{@item.price}"
   .de__price__money
    .de__price__money--tax
     (税込み)
    .de__price__money--deliver
     送料込み

  - if user_signed_in? && current_user.id == @item.user_id
   .de__price__edit
    = link_to "編集", edit_item_path(@item), method: :get, class: "de__price__edit--btn"
   .de__price__delete
    = link_to "削除", item_path(@item), method: :delete, class: "de__price__detete--btn"
  - else
   - if user_signed_in?
    .de__parchase
     =link_to '購入画面に進む',confirm_item_transaction_path(item_id: @item.id),class:'btn gobuy'
  .de__exp
   = @item.explanation
  .de__table
   %table.table
    %tbody
     %tr
      %th 出品者
      %td
       = @item.user.nickname
     %tr.table__category
      %th カテゴリー
      %td.table__category--td
       = link_to "#{@item.category.parent.parent.name}", '#'
       %br
       = link_to ">#{@item.category.parent.name}", '#'
       %br
       = link_to ">#{@item.category.name}", '#'
     %tr
      %th ブランド
      %td
       = @item.brand
     %tr
      %th 状態
      %td
       = @item.condition.name
     %tr
      %th 負担
      %td 
       = @item.delivery_charge.name
     %tr
      %th 地域
      %td 
       = @item.shipping_origin.name
     %tr
      %th 目安
      %td
       = @item.sending_days.name
  .de__good
   %button.de__good--button いいね！

 .comment
  =form_with local: true  do |comment|
   .comment__form
    =comment.text_field :title,class:'text-introduce',placeholder:'商品の說明を入力してください'
   .comment__caution
    マナーを守ってください!
   .comment__go
    =comment.submit 'コメントする',class: 'commentbutton'

 .item-front-and-back
  %li
   = link_to ""
   %i.fas.fa-chevron-left
    前の商品
  %li
   = link_to ""
   後の商品
   %i.fas.fa-chevron-right

= render 'footer'