config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
  }
  devise_scope :user do
    get 'addresses', to: 'users/registrations#new2'
    post 'addresses', to: 'users/registrations#new3'
  end
  root 'items#index'

  # itemコントローラーrouting
  resources :items do
    member do
      get 'category_children', defaults: { format: 'json' }
      get 'category_grandchildren', defaults: { format: 'json' }
    end

    resources :transactions do
      member do
        get  :confirm
        post :transacte
        get :carderror
      end
    end
    collection do
      get 'search'
    end
   
    
  end

  resources :users, only: [:show] do
    collection do
      get :logout
    end
  end 

  resources :card, only: [:new, :create, :show, :destroy]
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user

  validates :user_id, :customer_id, :card_id, presence: true
end

app/controllers/card_controller.rb
class CardController < ApplicationController
  require "payjp"
  before_action :set_card, only:[:new, :show, :destroy]

  def new
    if @card
      redirect_to action: :show, id: @card.id
    end
  end

  def create
    Payjp.api_key = Rails.application.credentials.PAYJP_SECRET_KEY
    if params["payjp_token"].blank?
      redirect_to action: :new
    else
      customer = Payjp::Customer.create(
        email: current_user.email,
        card: params["payjp_token"]
      )
      @card = Card.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)
      if @card.save
        redirect_to action: :show, id: @card.id
      else
        redirect_to action: :new
      end
    end
  end

  def show
    if @card.blank?
      redirect_to action: :new
    else
      Payjp.api_key = Rails.application.credentials.PAYJP_SECRET_KEY
      customer = Payjp::Customer.retrieve(@card.customer_id)
      @customer_card = customer.cards.retrieve(@card.card_id)
      @card_brand = @customer_card.brand
      case @card_brand
      when "Visa"
        @card_src = "cards/visa.svg"
      when "MasterCard"
        @card_src = "cards/master-card.svg"
      when "Saison"
        @card_src = "cards/saison-card.svg"
      when "JCB"
        @card_src = "cards/jcb.svg"
      when "American Express"
        @card_src = "cards/american_express.svg"
      when "Diners Club"
        @card_src = "cards/dinersclub.svg"
      when "Discover"
        @card_src = "cards/discover.svg"
      end
    end
  end

  def destroy
    if @card.destroy
      redirect_to new_card_path
    else
      redirect_to card_path(@card.id)
    end
  end

  private

  def set_card
    @card = Card.find_by(user_id: current_user.id)
  end
end

app/helpers/card_helper.rb
module CardHelper
end

app/views/card/_input.html.haml
.card-content
  %h2.card-content__title
    クレジットカード情報入力
  = form_with(url: card_index_path, local: true, class: "card-content__form", id: "charge-form") do |f|
    .card-content__form__body
      .card-form.card-form--1
        = f.label :number, "カード番号", class: "card-form__label"
        %span.must 必須
        = f.text_field :number, placeholder: "半角数字のみ",maxlength: "16", class: "card-form__input", id: 'number'
      %ul.card-icon-lists
        %li
          = image_tag 'cards/visa.svg', width:'49px', height: '20px', class: 'visa'
        %li
          = image_tag 'cards/master-card.svg', width:'34px', height: '20px', class: 'master'
        %li
          = image_tag 'cards/saison-card.svg', width:'30px', height: '20px', class: 'saison'
        %li
          = image_tag 'cards/jcb.svg', width:'32px', height: '20px', class: 'saison'
        %li
          = image_tag 'cards/american_express.svg', width:'21px', height: '20px', class: 'amex'
        %li
          = image_tag 'cards/dinersclub.svg', width:'32px', height: '20px', class: 'diners'
        %li
          = image_tag 'cards/discover.svg', width:'32px', height: '20px', class: 'discover'
      .card-form
        = f.label "有効期限", class: "card-form__label"
        %span.must 必須
        .card-form__select
          .card-form__select__half
            = f.select :exp_month, ['01', '02', '03', '04', '05', '06', '07', '08', '09', '10', '11', '12'], id: 'exp_month'
            %i.fas.fa-angle-down
            %span 月
          .card-form__select__half
            = f.select :exp_year, ['20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '30'], id: 'exp_year'
            %i.fas.fa-angle-down
            %span 年

      .card-form
        = f.label :cvc, "セキュリティコード", class: "card-form__label"
        %span.must 必須
        = f.text_field :cvc, placeholder: "カード背面４桁もしくは３桁の番号", maxlength: "4", class: "card-form__input", id: 'cvc'
        .card-form__cvc-explanation
          .card-form__cvc-explanation__toggle
            %span.question-icon ? 
            カード裏面の番号とは？
          .card-form__cvc-explanation__information
          
      = f.submit "追加する", class: "card-submit", id: "payment_card_submit-button"

app/views/card/_registerd_card.html.haml
.card-content
  %h2.card-content__title
    支払い方法
  .card-content__main
    .card-title
      %h3.card-title__letter クレジットカード
    .card-body
      .card-body__left
        .card-image
          = image_tag @card_src, width:'49px', height: '20px', class: 'visa'
        .card-number
          **** **** **** #{@customer_card.last4}
        .card-deadline
          #{@customer_card.exp_month.to_s} / #{@customer_card.exp_year.to_s.slice(2,3)}
      .card-body__right
        = link_to card_path, method: :delete, class: "card-remove" do
          削除する

app/views/card/create.html.haml
登録完了しました

app/views/card/new.html.haml
= render "items/header"
- breadcrumb :cards
= render "users/breadcrumb"
.mypage-main-conent
  .mypage-main-index
    = render "users/leftbar"
  .right-content
    = render "card/input"

= render "items/footer"

app/views/card/show.html.haml
= render "items/header"
- breadcrumb :card
= render "users/breadcrumb"
.mypage-main-conent
  .mypage-main-index
    = render "users/leftbar"
  .right-content
    = render "card/registerd_card"

= render "items/footer"