config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
  }
  devise_scope :user do
    get 'addresses', to: 'users/registrations#new2'
    post 'addresses', to: 'users/registrations#new3'
  end
  root 'items#index'

  # itemコントローラーrouting
  resources :items do
    member do
      get 'category_children', defaults: { format: 'json' }
      get 'category_grandchildren', defaults: { format: 'json' }
    end

    resources :transactions do
      member do
        get  :confirm
        post :transacte
        get :carderror
      end
    end
    collection do
      get 'search'
    end
   
    
  end

  resources :users, only: [:show] do
    collection do
      get :logout
    end
  end 

  resources :card, only: [:new, :create, :show, :destroy]
end

app/controllers/transaction_controller.rb
class TransactionController < ApplicationController
  def buy
    
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  require "payjp"
  before_action :set_item
  before_action :set_card

  def confirm
    if @card.present?
      Payjp.api_key = Rails.application.credentials.PAYJP_SECRET_KEY
      customer = Payjp::Customer.retrieve(@card.customer_id)
      @customer_card = customer.cards.retrieve(@card.card_id)
      @card_brand = @customer_card.brand
      case @card_brand
      when "Visa"
        @card_src = "cards/visa.svg"
      when "MasterCard"
        @card_src = "cards/master-card.svg"
      when "Saison"
        @card_src = "cards/saison-card.svg"
      when "JCB"
        @card_src = "cards/jcb.svg"
      when "American Express"
        @card_src = "cards/american_express.svg"
      when "Diners Club"
        @card_src = "cards/dinersclub.svg"
      when "Discover"
        @card_src = "cards/discover.svg"
      end
    end
  end

  def transacte
    if @item.tx.present?
      redirect_to item_path(@item.id)
    else
      ActiveRecord::Base.transaction do
        @item.with_lock do
          Payjp.api_key = Rails.application.credentials.PAYJP_SECRET_KEY
          charge = Payjp::Charge.create(
            amount: @item.price,
            customer: Payjp::Customer.retrieve(@card.customer_id),
            currency: 'jpy'
          )
        @transacte = Transaction.create(buyer_id: current_user.id, item_id: params[:item_id], seller_id: @item.user_id)
        @item.update(transaction_status: 0)
        end
      #失敗したときの処理
      rescue => e
        # redirect_to card_path(@card.id)
        redirect_to carderror_item_transaction_path(@card.id)
      end
    end
  end


  private

  def set_item
    @item = Item.find(params[:id])
  end

  def set_card
    @card = Card.find_by(user_id: current_user.id)
  end
end

app/helpers/transaction_helper.rb
module TransactionHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/buy.htm.haml
= render 'header'
.wrapper-item
 .pa
  .pa__confirm
   .pa__confirm__box
    購入内容の確認
  .pa__item
   .pa__item__box
    .pa__item__box__left
     ここに画像を載せる
    .pa__item__box__right
     .pa__item__box__right--name
      商品名
     .pa__item__box__right__money
      .pa__item__box__right__money--price
       ¥1,500,000
      .pa__item__box__right__money--tax
       税込　送料込み
  .pa__trade
   .pa__trade__money
    .pa__trade__money--in
     金額
    .pa__trade__money--total
     ここに金額を表示
   .pa__trade__pay
    .pa__trade__pay__how
     .pa__trade__pay__how--in
      支払方法
     .pa__trade__pay__how--select
      =link_to 'カード選択','#'
    .pa__trade__pay__card
     .pa__trade__pay__card--in
      使用するカード
     .pa__trade__pay__card__credit
      .pa__trade__pay__card__credit--number
       .pa__trade__pay__card__credit--number--in
        カード番号
        .pa__trade__pay__card__credit--number--out
         ここにカード番号を表示
      .pa__trade__pay__card__credit--limit
       .pa__trade__pay__card__credit--limit
        有効期限
       .pa__trade__pay__card__credit--limit
        ここに有効期限を表示
   .pa__trade__deliver
    .pa__trade__deliver__box
     .pa__trade__deliver__box__toward
      .pa__trade__deliver__box__toward--in
       配送先
      .pa__trade__deliver__box__toward--change
       変更する
     .pa__trade__deliver__box--place1
      住所1
     .pa__trade__deliver__box--place2
      住所2
     .pa__trade__deliver__box--place3
      住所3
     .pa__trade__deliver__box--place4
      住所4
     .pa__trade__deliver__box--name
      氏名
  .pa__go
   .pa__go--button
    %button.gobutton 購入する
= render 'footer'

app/views/transactions/carderror.html.haml
= render 'items/header'
.wrapper-item
 .pa
  .pa__confirm
   .pa__confirm__ngbox
    取引に失敗しました。
  .pa__item__errorintro
   通信環境の良いところで再度お試しください。
  .pa__item__errorintro
   もしくは、カード情報に問題がある可能性があります。
  .pa__bottom
   = link_to "カード設定画面へ", card_path(@card.id), class:"pa__bottom__errorbutton"
= render 'items/banner'
= render 'items/footer'
= render 'items/exhibition-btn'

app/views/transactions/confirm.haml.haml
= render 'header'
.wrapper-item
 .pa
  .pa__confirm
   .pa__confirm__box
    購入内容の確認
  .pa__item
   .pa__item__box
    .pa__item__box__left
     ここに画像を載せる
    .pa__item__box__right
     .pa__item__box__right--name
      商品名
     .pa__item__box__right__money
      .pa__item__box__right__money--price
       ¥1,500,000
      .pa__item__box__right__money--tax
       税込　送料込み
  .pa__trade
   .pa__trade__money
    .pa__trade__money--in
     金額
    .pa__trade__money--total
     ここに金額を表示
   .pa__trade__pay
    .pa__trade__pay__how
     .pa__trade__pay__how--in
      支払方法
     .pa__trade__pay__how--select
      =link_to 'カード選択','#'
    .pa__trade__pay__card
     .pa__trade__pay__card--in
      使用するカード
     .pa__trade__pay__card__credit
      .pa__trade__pay__card__credit--number
       .pa__trade__pay__card__credit--number--in
        カード番号
        .pa__trade__pay__card__credit--number--out
         ここにカード番号を表示
      .pa__trade__pay__card__credit--limit
       .pa__trade__pay__card__credit--limit
        有効期限
       .pa__trade__pay__card__credit--limit
        ここに有効期限を表示
   .pa__trade__deliver
    .pa__trade__deliver__box
     .pa__trade__deliver__box__toward
      .pa__trade__deliver__box__toward--in
       配送先
      .pa__trade__deliver__box__toward--change
       変更する
     .pa__trade__deliver__box--place1
      住所1
     .pa__trade__deliver__box--place2
      住所2
     .pa__trade__deliver__box--place3
      住所3
     .pa__trade__deliver__box--place4
      住所4
     .pa__trade__deliver__box--name
      氏名
  .pa__go
   .pa__go--button
    %button.gobutton 購入する
= render 'footer'

app/views/transactions/confirm.html.haml
= render 'items/header'
.wrapper-item
 .pa
  .pa__confirm
   .pa__confirm__box
    購入内容の確認
  .pa__item
   .pa__item__box
    .pa__item__box__left
     = image_tag "#{@item.item_images.first.image}", width: "90", height: "90"
    .pa__item__box__right
     .pa__item__box__right--name
      =@item.name
     .pa__item__box__right__money
      .pa__item__box__right__money--price
       = "¥#{@item.price}"
      .pa__item__box__right__money--tax
       税込  送料込み
  .pa__trade
   .pa__trade__money
    .pa__trade__money--in
     金額
    .pa__trade__money--total
     = "¥#{@item.price}"
   .pa__trade__pay
    .pa__trade__pay__how
     .pa__trade__pay__how--in
      支払方法

    .pa__trade__pay__card
     .pa__trade__pay__card--in
     - if @card.present?
      クレジットカード
      .pa__trade__pay__card__credit
       .pa__trade__pay__card__credit--number
        .pa__trade__pay__card__credit--number--in
         カード番号
         .pa__trade__pay__card__credit--number--out
          **** **** **** #{@customer_card.last4}
        .pa__trade__pay__card__credit--limit
         有効期限
        .pa__trade__pay__card__credit--limit
         #{@customer_card.exp_month.to_s} / #{@customer_card.exp_year.to_s.slice(2,3)}
        .pa__trade__pay__card__credit--logo
         = image_tag @card_src, width:'49px', height: '20px', class: 'visa'
     - else
      クレジットカードが登録されていません
   .pa__trade__deliver
    .pa__trade__deliver__box
     .pa__trade__deliver__box__toward
      .pa__trade__deliver__box__toward--in
       配送先
     .pa__trade__deliver__box--place1
      =current_user.address.prefecture.name
     .pa__trade__deliver__box--place2
      =current_user.address.city
     .pa__trade__deliver__box--place3
      =current_user.address.town
     .pa__trade__deliver__box--place4
      =current_user.address.building
     .pa__trade__deliver__box--name
      =current_user.nickname
  .pa__go
   .pa__go--button
    - if @card.present?
     = link_to "購入する", transacte_item_transaction_path, method: :post, class: "gobutton"
    - else
     .pa__go--button.cantgobutton カード登録をしてください

= render 'items/footer'

app/views/transactions/transacte.html.haml
= render 'items/header'
.wrapper-item
 .pa
  .pa__confirm
   .pa__confirm__box
    購入が完了しました
  .pa__item
   .pa__item__box
    .pa__item__box__left
     = image_tag "#{@item.item_images.first.image}", width: "90", height: "90"
    .pa__item__box__right
     .pa__item__box__right--name
      =@item.name
     .pa__item__box__right__money
      .pa__item__box__right__money--price
       = "¥#{@item.price}"
      .pa__item__box__right__money--tax
       税込  送料込み
  .pa__trade
   .pa__trade__money
    .pa__trade__money--in
     金額
    .pa__trade__money--total
     = "¥#{@item.price}"
  .pa__bottom
   = link_to "トップページへ戻る", root_path, class:"pa__bottom__button"

= render 'items/banner'
= render 'items/footer'
= render 'items/exhibition-btn'